- hosts: localhost
  connection: local
  gather_facts: true
  pre_tasks:
    - name: Load repository data
      load_repo:
        path: "{{ lookup('env', 'PWD') }}"
  roles:
    - role: migrations
      tags: [migrations]
    - role: github
      tags: [github]
    - role: docs
      tags: [docs]
    - role: php
      tags: php
    - role: docker
      tags: docker
    # - name: Execute tasks for applications, libraries, and symfony-bundles
    #   block:
    #   - import_tasks: tasks/other-dev-generated-files.yaml
    #   when: >
    #     repo.type in ['application', 'library', 'symfony-bundle']
    #     or repo.type.startswith('php-') or repo.type.startswith('nodejs-')