- hosts: all
  connection: local
  vars:
    base_path: "{{ lookup('env', 'REPO_ANSIBLE_BASE_PATH') or (playbook_dir + '/workspace') }}"
    repo_path: "{{ base_path }}/{{ inventory_hostname }}"
    changes: "{{ lookup('env', 'REPO_ANSIBLE_CHANGES') }}"
    skip_checkout: "{{ lookup('env', 'REPO_ANSIBLE_SKIP_CHECKOUT')|default(False) }}"
  tasks:
    - import_tasks: tasks/checkout.yaml
      vars:
        repository: "{{ inventory_hostname }}"
        destination: "{{ repo_path }}"
      when: not skip_checkout
      tags: checkout

    - import_tasks: tasks/version-migrations.yaml
    - import_tasks: tasks/retrieve-validate-repo-data.yaml

    - import_tasks: tasks/retrieve-docs-data.yaml
    - import_tasks: tasks/generate-files.yaml

    - name: Execute tasks for applications, libraries, and symfony-bundles
      block:
        - import_tasks: tasks/devcontainer.yaml
        - import_tasks: tasks/other-dev-generated-files.yaml
      when: >
        repo.type in ['application', 'library', 'symfony-bundle']
        or repo.type.startswith('php-') or repo.type.startswith('nodejs-')

    - import_tasks: tasks/php-qa.yaml
      when: >
        repo.type in ['application', 'library', 'symfony-bundle']
        or repo.type.startswith('php-')

    - import_tasks: tasks/pull-request.yaml
      when: changes == 'pull-request'
      tags: commit-changes

    - import_tasks: tasks/push.yaml
      when: changes == 'push'
      tags: commit-changes
