[project]
name = "repo-ansible"
version = "0.18.0"
description = "Ansible playbooks with templated configuration to apply to all LinkORB"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "ansible>=11.9.0",
    "jsonschema>=4.25.1",
]
