- name: Create .github directory
  ansible.builtin.file:
    path: "{{ repo_extras.path }}/.github"
    state: directory

- name: Generate SECURITY.md file
  ansible.builtin.template:
    src: SECURITY.md.j2
    dest: "{{ repo_extras.path }}/.github/SECURITY.md"

- name: Generate .github/settings.yml
  ansible.builtin.template:
    src: settings.yml.j2
    dest: "{{ repo_extras.path }}/.github/settings.yml"

- name: Generate .github/workflows directory
  ansible.builtin.file:
    path: "{{ repo_extras.path }}/.github/workflows"
    state: directory

- name: Generate repo-ansible workflow
  ansible.builtin.template:
    src: workflows/auto-run-repo-ansible.yaml.j2
    dest: "{{ repo_extras.path }}/.github/workflows/auto-run-repo-ansible.yaml"
    variable_start_string: '[['
    variable_end_string: ']]'

- name: Generate pull request labeling workflow
  ansible.builtin.template:
    src: workflows/auto-label-pull-request.yaml.j2
    dest: "{{ repo_extras.path }}/.github/workflows/auto-label-pull-request.yaml"
    variable_start_string: '[['
    variable_end_string: ']]'

- name: Generate dependabot automerge workflow
  ansible.builtin.template:
    src: workflows/auto-merge-dependabot-prs.yaml.j2
    dest: "{{ repo_extras.path }}/.github/workflows/auto-merge-dependabot-prs.yaml"
    variable_start_string: '[['
    variable_end_string: ']]'
  when: repo.github.features.dependabot_auto_merge

- name: Generate CODEOWNERS file
  ansible.builtin.template:
    src: CODEOWNERS.j2
    dest: "{{ repo_extras.path }}/.github/CODEOWNERS"
  vars:
    codeowners: "{{ repo.codeowners }}"

- name: Generate CODE_OF_CONDUCT file
  ansible.builtin.template:
    src: CODE_OF_CONDUCT.md.j2
    dest: "{{ repo_extras.path }}/.github/CODE_OF_CONDUCT.md"

- when: repo.github.workflows.review
  block:
  - name: Set dictionary of extension workflows
    list_extension_workflows:
      prefix: "{{ repo_extras.path }}/.github/workflows"
    changed_when: false

- when: repo.github.features.sdlc_workflows
  block:
  - name: generate semantic-release config file
    ansible.builtin.template:
      src: .releaserc.cjs.j2
      dest: "{{ repo_extras.path }}/.releaserc.cjs"
    vars:
      package_json_version_bump: "{{ repo.type.startswith('nodejs-') or 'package.json' in repo.github_workflows.release.commit_changed_files }}"

  - name: copy github actions workflow files
    ansible.builtin.template:
      src: workflows/{{ item.target }}.j2
      dest: "{{ repo_extras.path }}/.github/workflows/{{ item.target }}"
      variable_start_string: '[['
      variable_end_string: ']]'
    vars:
      workflow_group: "{{ item.workflow_group }}"
      followup_workflows: "{{ extension_workflows }}"
      docker_build_args: "{{ default_docker_build_args | combine(repo.github_workflows.build.extra_docker_build_args) }}"
    loop:
      - target: 10-review.yaml
        workflow_group: "10"
      - target: 30-release-and-build.yaml
        workflow_group: "30"
      - target: 50-security.yaml
        workflow_group: "50"
      - target: 90-cleanup.yaml
        workflow_group: "90"